
# This file is automatically generated, you probably don't want to edit this

Comp2ROptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "Comp2ROptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            r1 = NULL,
            n1 = NULL,
            r2 = NULL,
            n2 = NULL,
            alt = "bilateral", ...) {

            super$initialize(
                package="FEExtra",
                name="Comp2R",
                requiresData=FALSE,
                ...)

            private$..r1 <- jmvcore::OptionNumber$new(
                "r1",
                r1,
                min=-1,
                max=1)
            private$..n1 <- jmvcore::OptionNumber$new(
                "n1",
                n1)
            private$..r2 <- jmvcore::OptionNumber$new(
                "r2",
                r2,
                min=-1,
                max=1)
            private$..n2 <- jmvcore::OptionNumber$new(
                "n2",
                n2)
            private$..alt <- jmvcore::OptionList$new(
                "alt",
                alt,
                options=list(
                    "bilateral",
                    "tud",
                    "tue"),
                default="bilateral")

            self$.addOption(private$..r1)
            self$.addOption(private$..n1)
            self$.addOption(private$..r2)
            self$.addOption(private$..n2)
            self$.addOption(private$..alt)
        }),
    active = list(
        r1 = function() private$..r1$value,
        n1 = function() private$..n1$value,
        r2 = function() private$..r2$value,
        n2 = function() private$..n2$value,
        alt = function() private$..alt$value),
    private = list(
        ..r1 = NA,
        ..n1 = NA,
        ..r2 = NA,
        ..n2 = NA,
        ..alt = NA)
)

Comp2RResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "Comp2RResults",
    inherit = jmvcore::Group,
    active = list(
        comp2R = function() private$.items[["comp2R"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="")
            self$add(jmvcore::Table$new(
                options=options,
                name="comp2R",
                title="Compara\u00E7\u00E3o de duas correla\u00E7\u00F5es",
                rows=1,
                columns=list(
                    list(
                        `name`="r1", 
                        `title`="r1", 
                        `type`="number"),
                    list(
                        `name`="r2", 
                        `title`="r2", 
                        `type`="number"),
                    list(
                        `name`="Z", 
                        `title`="z", 
                        `type`="number"),
                    list(
                        `name`="P", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))}))

Comp2RBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "Comp2RBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FEExtra",
                name = "Comp2R",
                version = c(1,0,0),
                options = options,
                results = Comp2RResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

#' Comparação de duas Correlações
#'
#' 
#' @param r1 .
#' @param n1 .
#' @param r2 .
#' @param n2 .
#' @param alt .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$comp2R} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$comp2R$asDF}
#'
#' \code{as.data.frame(results$comp2R)}
#'
#' @export
Comp2R <- function(
    r1,
    n1,
    r2,
    n2,
    alt = "bilateral") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Comp2R requires jmvcore to be installed (restart may be required)")


    options <- Comp2ROptions$new(
        r1 = r1,
        n1 = n1,
        r2 = r2,
        n2 = n2,
        alt = alt)

    analysis <- Comp2RClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

