
# This file is automatically generated, you probably don't want to edit this

FrdTestOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FrdTestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            posts = "Nenhum",
            method = "bonferroni", ...) {

            super$initialize(
                package="FEExtra",
                name="FrdTest",
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars,
                required=TRUE,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..posts <- jmvcore::OptionList$new(
                "posts",
                posts,
                options=list(
                    "Nenhum",
                    "Dunn",
                    "Durbin-Conover"),
                default="Nenhum")
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "bonferroni",
                    "holm",
                    "BH"),
                default="bonferroni")

            self$.addOption(private$..vars)
            self$.addOption(private$..posts)
            self$.addOption(private$..method)
        }),
    active = list(
        vars = function() private$..vars$value,
        posts = function() private$..posts$value,
        method = function() private$..method$value),
    private = list(
        ..vars = NA,
        ..posts = NA,
        ..method = NA)
)

FrdTestResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FrdTestResults",
    inherit = jmvcore::Group,
    active = list(
        Frd = function() private$.items[["Frd"]],
        dunn = function() private$.items[["dunn"]],
        durbin = function() private$.items[["durbin"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Teste de Friedman com Post-Hocs")
            self$add(jmvcore::Table$new(
                options=options,
                name="Frd",
                title="Teste de Friedman",
                rows=1,
                visible=TRUE,
                clearWith=list(
                    "vars"),
                columns=list(
                    list(
                        `name`="chiSq", 
                        `title`="Fr", 
                        `type`="number"),
                    list(
                        `name`="df", 
                        `title`="gl", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="Pasymp", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="px", 
                        `title`="Pexact", 
                        `type`="number"),
                    list(
                        `name`="es", 
                        `title`="\u03C9", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="dunn",
                title="Teste Post-hoc de Dunn para amostras emparelhadas",
                rows="nComps",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Compara\u00E7\u00E3o", 
                        `type`="text"),
                    list(
                        `name`="Z", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="Padj", 
                        `title`="Paj", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="durbin",
                title="Testes Post-hoc de Durbin-Conover",
                rows="nComps",
                visible=FALSE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Compara\u00E7\u00E3o", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `type`="number"),
                    list(
                        `name`="P", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="Padj", 
                        `title`="Paj", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Box Plots",
                visible=FALSE,
                width=450,
                height=300,
                renderFun=".plot"))}))

FrdTestBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "FrdTestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FEExtra",
                name = "FrdTest",
                version = c(1,0,0),
                options = options,
                results = FrdTestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Teste de Friedman com Post-Hocs
#'
#' 
#' @param data .
#' @param vars As medidas repetidas. Têm que ser pelo menos ordinal.
#' @param posts Teste de Dunn sem correção e com correção a escolher
#'   (Bonferroni-Dunn é a mais usual)
#' @param method .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$Frd} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$dunn} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$durbin} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$Frd$asDF}
#'
#' \code{as.data.frame(results$Frd)}
#'
#' @export
FrdTest <- function(
    data,
    vars,
    posts = "Nenhum",
    method = "bonferroni") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("FrdTest requires jmvcore to be installed (restart may be required)")

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- FrdTestOptions$new(
        vars = vars,
        posts = posts,
        method = method)

    analysis <- FrdTestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

