
# This file is automatically generated, you probably don't want to edit this

ICVARSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ICVARSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            group = NULL,
            ci = 0.95, ...) {

            super$initialize(
                package="FEExtra",
                name="ICVARS",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..group <- jmvcore::OptionVariable$new(
                "group",
                group)
            private$..ci <- jmvcore::OptionNumber$new(
                "ci",
                ci,
                min=0.01,
                max=0.99,
                default=0.95)

            self$.addOption(private$..dep)
            self$.addOption(private$..group)
            self$.addOption(private$..ci)
        }),
    active = list(
        dep = function() private$..dep$value,
        group = function() private$..group$value,
        ci = function() private$..ci$value),
    private = list(
        ..dep = NA,
        ..group = NA,
        ..ci = NA)
)

ICVARSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ICVARSResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        icvars = function() private$.items[["icvars"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Intervalo de Confian\u00E7a para Vari\u00E2ncias"))
            self$add(jmvcore::Table$new(
                options=options,
                name="icvars",
                title="Intervalo de Confian\u00E7a para Vari\u00E2ncias",
                rows=3,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="group", 
                        `title`="Grupo", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `type`="integer"),
                    list(
                        `name`="Variance", 
                        `title`="Vari\u00E2ncia", 
                        `type`="number"),
                    list(
                        `name`="Lower", 
                        `title`="Lim. Inf.", 
                        `type`="number"),
                    list(
                        `name`="Upper", 
                        `title`="Lim. Sup.", 
                        `type`="number"))))}))

ICVARSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ICVARSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "FEExtra",
                name = "ICVARS",
                version = c(1,0,0),
                options = options,
                results = ICVARSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Intervalo de Confiança para Variâncias
#'
#' 
#' @param data .
#' @param dep .
#' @param group .
#' @param ci .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$icvars} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$icvars$asDF}
#'
#' \code{as.data.frame(results$icvars)}
#'
#' @export
ICVARS <- function(
    data,
    dep,
    group,
    ci = 0.95) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("ICVARS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(group)) group <- jmvcore::resolveQuo(jmvcore::enquo(group))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(group), group, NULL))


    options <- ICVARSOptions$new(
        dep = dep,
        group = group,
        ci = ci)

    analysis <- ICVARSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

